version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oasisdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    image: oasisai-api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/oasisdb
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data: