services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oasisdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
  api:
    image: oasisai-api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/oasisdb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data: